sonar.projectKey=nexusmarket-advanced-micro-frontend-e-commerce
sonar.projectName=Nuxus Shopping - Advanced Micro-Frontend E-Commerce
sonar.projectVersion=1.0.0

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.inclusions=**/*.js,**/*.jsx,**/*.ts,**/*.tsx,**/*.css,**/*.html
sonar.javascript.file.suffixes=.js,.jsx,.cjs,.mjs
sonar.typescript.file.suffixes=.ts,.tsx

sonar.exclusions=node_modules/**,dist/**,.git/**,.scannerwork/**,coverage/**,kubernetes/**,.github/**,.dockerignore,.gitignore,.env.local,package-lock.json