apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml

commonLabels:
  app.kubernetes.io/name: nexus-market
  app.kubernetes.io/part-of: nexus-market
  managed-by: kustomize

images:
  - name: nexus-market
    newName: lokeshzenbook/node-app09
    newTag: latest
