apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nexus-market
  labels:
    app.kubernetes.io/name: nexus-market
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nexus-market
